//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkerRole.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class Area
    {
        public Area()
        {
            this.PlayerHouses = new HashSet<PlayerHouses>();
        }
    
        public int Id { get; set; }
        public string NoOfHouses { get; set; }
    
        public virtual ICollection<PlayerHouses> PlayerHouses { get; set; }
    }
}
