//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkerRole.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class Player
    {
        public Player()
        {
            this.Scoreboard = new HashSet<Scoreboard>();
            this.Session = new HashSet<Session>();
            this.PlayerHouses = new HashSet<PlayerHouses>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Scoreboard> Scoreboard { get; set; }
        public virtual ICollection<Session> Session { get; set; }
        public virtual ICollection<PlayerHouses> PlayerHouses { get; set; }
    }
}
