//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkerRole.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class Scoreboard
    {
        public Scoreboard()
        {
            this.Player = new HashSet<Player>();
        }
    
        public int Id { get; set; }
        public int Score { get; set; }
    
        public virtual ICollection<Player> Player { get; set; }
        public virtual Session Session { get; set; }
    }
}
