//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkerRole.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class Session
    {
        public Session()
        {
            this.Player = new HashSet<Player>();
            this.PlayerHouses = new HashSet<PlayerHouses>();
        }
    
        public int Id { get; set; }
        public System.DateTime StartDateTime { get; set; }
        public System.DateTime EndDateTime { get; set; }
    
        public virtual ICollection<Player> Player { get; set; }
        public virtual Scoreboard Scoreboard { get; set; }
        public virtual ICollection<PlayerHouses> PlayerHouses { get; set; }
    }
}
